// app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { Teko } from "next/font/google";
import Navbar from "@/pages/components/Navbar";
import Footer from "@/pages/components/Footer";
import AnimatedContentWrapper from "@/pages/components/AnimatedContentWrapper";

const teko = Teko({
  display: "swap",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${teko.className} flex flex-col min-h-screen`}>
        <Providers>
          <Navbar />
          <AnimatedContentWrapper>{children}</AnimatedContentWrapper>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
